# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('student_id', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('dob', models.CharField(max_length=300)),
                ('joining', models.CharField(max_length=300)),
                ('Class', models.CharField(max_length=300)),
                ('section', models.CharField(max_length=300)),
                ('guardian', models.CharField(max_length=300)),
            ],
        ),
    ]
