# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Discription', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.CreateModel(
            name='Addteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Teacher_id', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('Salary', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=30)),
                ('Date_of_joining', models.CharField(max_length=30)),
                ('DOB', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Examnotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('Discription', models.CharField(max_length=30)),
                ('Date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ptaauthorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Occupation', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Studentfees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_number', models.CharField(max_length=30)),
                ('Student', models.CharField(max_length=30)),
                ('Fees', models.CharField(max_length=30)),
            ],
        ),
    ]
