# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
    ]
